# Generated by Django 5.1.1 on 2024-12-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('producto', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('id_sucursal', models.PositiveIntegerField()),
            ],
        ),
    ]
