# Generated by Django 5.1.1 on 2024-12-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('calle_sucursal', models.CharField(max_length=255)),
                ('num_empleados', models.PositiveIntegerField()),
                ('tel_sucursal', models.PositiveIntegerField()),
            ],
        ),
    ]
