# Generated by Django 5.1.1 on 2024-12-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.PositiveIntegerField()),
                ('codigo_p', models.CharField(max_length=20)),
            ],
        ),
    ]
